#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#   Matthew de Verteuil <mverteuil@github.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# ------------- Customize below -------------

# Initialize nodenv, if it exists
if command -v nodenv 1>/dev/null 2>&1; then
  eval "$(nodenv init -)"
fi

# Initialize pyenv, if it exists
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
  pyenv virtualenvwrapper
fi

# Load iTerm2 shell integration, if it exists
if [[ -f "${ZDOTDIR:-$HOME}/.iterm2_shell_integration.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.iterm2_shell_integration.zsh"
fi

# Allow file clobbering
setopt CLOBBER

# Load base16 shell integration, if it exists
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# Project switcher
if test ! -z $PROJECT_HOME; then
    function project () {
        cd $PROJECT_HOME/$1
    }

    # Project switched completion
    function _project () {
        _path_files -/ -W $PROJECT_HOME
    }

    compdef _project project
else
    echo "------\nERROR: Project home was not set, project switcher not loaded.\n------\n"
fi

